package com.example.demo.controllers;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import com.example.demo.DTO.BloodRequestDTO;
import com.example.demo.entities.BloodRequest;
import com.example.demo.services.BloodRequestService;

@CrossOrigin(origins = "http://localhost:3000")
@RestController
@RequestMapping("/api/request")
public class BloodRequestController {

    @Autowired
    private BloodRequestService bloodRequestService;

    // Get all requests
    @GetMapping
    public List<BloodRequest> getAll() {
        return bloodRequestService.getAllRequest();
    }

    // Get requested blood summary
    @GetMapping("/blood")
    public List<Map<String, Object>> getRequests() {
        return bloodRequestService.getRequestedBlood();
    }

    // ✅ Save new blood request (DTO-based)
//    @PostMapping("/saverequest")
//    public BloodRequest saveRequest(@RequestBody BloodRequestDTO dto) {
//        return bloodRequestService.saveRequest(dto);
//    }
    
    @PostMapping("/saverequest")
    public BloodRequest saveRequest(@RequestBody BloodRequestDTO dto) {
        // Manually assign user ID until JWT is implemented
        dto.setUserid(28); // <-- replace 28 with the default/test user ID
        return bloodRequestService.saveRequest(dto);
    }
    
    
    
 // ✅ NEW: Get all requests EXCLUDING requests generated by itself
    @GetMapping("/all-except/{userid}")
    public List<BloodRequest> getAllExceptLoggedInUser(@PathVariable int userid) {
        return bloodRequestService.getAllRequestsExceptCurrentUser(userid);
    }

    
    
}
